# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\jdid\nv-medecin\editer_maladie.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(362, 224)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.maladie = QtWidgets.QComboBox(self.centralwidget)
        self.maladie.setObjectName("maladie")
        self.gridLayout.addWidget(self.maladie, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.nv_maladie = QtWidgets.QLineEdit(self.centralwidget)
        self.nv_maladie.setObjectName("nv_maladie")
        self.gridLayout.addWidget(self.nv_maladie, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.valider = QtWidgets.QPushButton(self.centralwidget)
        self.valider.setObjectName("valider")
        self.horizontalLayout.addWidget(self.valider)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.fermer = QtWidgets.QPushButton(self.centralwidget)
        self.fermer.setObjectName("fermer")
        self.horizontalLayout.addWidget(self.fermer)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 0, 1, 3)
        self.categorie = QtWidgets.QComboBox(self.centralwidget)
        self.categorie.setObjectName("categorie")
        self.gridLayout.addWidget(self.categorie, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ajouter Maladie"))
        self.label_2.setText(_translate("MainWindow", "Nouveau Maladie"))
        self.label_3.setText(_translate("MainWindow", "Maladies"))
        self.label.setText(_translate("MainWindow", "Categories"))
        self.valider.setText(_translate("MainWindow", "Valider"))
        self.fermer.setText(_translate("MainWindow", "Fermer"))
