# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\jdid\nv-medecin\modif_mdp.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(543, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 80, 521, 511))
        self.frame.setStyleSheet("QFrame\n"
"{\n"
"background:rgba(0,0,0,0.8);\n"
"border-radius: 15px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.modifier = QtWidgets.QPushButton(self.frame)
        self.modifier.setGeometry(QtCore.QRect(20, 400, 471, 51))
        self.modifier.setStyleSheet("QPushButton{\n"
"color:white;\n"
"border-radius:15px;\n"
"font-family:century gothiw ;\n"
"font-size:24px;}\n"
"\n"
"QPushButton:hover{\n"
"color:#333;\n"
"border-radius:15px;\n"
"background:red;\n"
"}")
        self.modifier.setObjectName("modifier")
        self.nv_mdp = QtWidgets.QLineEdit(self.frame)
        self.nv_mdp.setGeometry(QtCore.QRect(20, 290, 431, 31))
        self.nv_mdp.setStyleSheet("QLineEdit\n"
"{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"\n"
"font-family:century gothiw ;\n"
"font-size:24px;\n"
"border-bottom:1px solid #717072;\n"
"}")
        self.nv_mdp.setText("")
        self.nv_mdp.setEchoMode(QtWidgets.QLineEdit.Password)
        self.nv_mdp.setObjectName("nv_mdp")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(200, 70, 171, 71))
        self.label.setStyleSheet("*{\n"
"font-family:century gothiw ;\n"
"font-size:24px;\n"
"}\n"
"\n"
"QLabel {\n"
"color:white;\n"
"background:transparent;\n"
"}\n"
"\n"
"\n"
"")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 230, 241, 51))
        self.label_3.setStyleSheet("*{\n"
"font-family:century gothiw ;\n"
"font-size:24px;\n"
"}\n"
"\n"
"QLabel {\n"
"color:white;\n"
"background:transparent;\n"
"}\n"
"\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        self.effacer = QtWidgets.QPushButton(self.frame)
        self.effacer.setGeometry(QtCore.QRect(20, 460, 111, 31))
        self.effacer.setStyleSheet("QPushButton{\n"
"color:white;\n"
"border-radius:15px;\n"
"font-family:century gothiw ;\n"
"font-size:12px;}\n"
"\n"
"QPushButton:hover{\n"
"color:#333;\n"
"border-radius:15px;\n"
"background:red;\n"
"}")
        self.effacer.setObjectName("effacer")
        self.rmdp = QtWidgets.QLineEdit(self.frame)
        self.rmdp.setGeometry(QtCore.QRect(20, 360, 431, 31))
        self.rmdp.setStyleSheet("QLineEdit\n"
"{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"\n"
"font-family:century gothiw ;\n"
"font-size:24px;\n"
"border-bottom:1px solid #717072;\n"
"}")
        self.rmdp.setText("")
        self.rmdp.setEchoMode(QtWidgets.QLineEdit.Password)
        self.rmdp.setObjectName("rmdp")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 241, 51))
        self.label_4.setStyleSheet("*{\n"
"font-family:century gothiw ;\n"
"font-size:24px;\n"
"}\n"
"\n"
"QLabel {\n"
"color:white;\n"
"background:transparent;\n"
"}\n"
"\n"
"\n"
"")
        self.label_4.setObjectName("label_4")
        self.mdp = QtWidgets.QLineEdit(self.frame)
        self.mdp.setGeometry(QtCore.QRect(20, 190, 431, 31))
        self.mdp.setStyleSheet("QLineEdit\n"
"{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"\n"
"font-family:century gothiw ;\n"
"font-size:24px;\n"
"border-bottom:1px solid #717072;\n"
"}")
        self.mdp.setText("")
        self.mdp.setEchoMode(QtWidgets.QLineEdit.Password)
        self.mdp.setObjectName("mdp")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(200, 20, 141, 121))
        self.toolButton.setStyleSheet("#toolButton\n"
"\n"
"{\n"
"background:red;\n"
"border-radius:60px;\n"
"}")
        self.toolButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/HP/Pictures/Camera Roll/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(50, 60))
        self.toolButton.setObjectName("toolButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Modifier le mot de passe"))
        self.modifier.setText(_translate("MainWindow", "Modifier"))
        self.nv_mdp.setPlaceholderText(_translate("MainWindow", "Nv mot de passe"))
        self.label.setText(_translate("MainWindow", "Modification"))
        self.label_3.setText(_translate("MainWindow", "Nv mot de passe :"))
        self.effacer.setText(_translate("MainWindow", "Tout Effacer"))
        self.rmdp.setPlaceholderText(_translate("MainWindow", "Retapez le nv mot de passe"))
        self.label_4.setText(_translate("MainWindow", "Mot de passe :"))
        self.mdp.setPlaceholderText(_translate("MainWindow", "Mot de passe"))
