# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\HP\Desktop\dernier version md\rendez_vous.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(572, 446)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rdv = QtWidgets.QTableWidget(self.centralwidget)
        self.rdv.setGeometry(QtCore.QRect(20, 60, 541, 331))
        self.rdv.setObjectName("rdv")
        self.rdv.setColumnCount(3)
        self.rdv.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.rdv.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rdv.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rdv.setHorizontalHeaderItem(2, item)
        self.rdv.horizontalHeader().setDefaultSectionSize(160)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 47, 13))
        self.label.setObjectName("label")
        self.date = QtWidgets.QDateEdit(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(100, 20, 191, 22))
        self.date.setObjectName("date")
        self.supprimer = QtWidgets.QPushButton(self.centralwidget)
        self.supprimer.setGeometry(QtCore.QRect(130, 400, 75, 23))
        self.supprimer.setObjectName("supprimer")
        self.ajouter = QtWidgets.QPushButton(self.centralwidget)
        self.ajouter.setGeometry(QtCore.QRect(240, 400, 75, 23))
        self.ajouter.setObjectName("ajouter")
        self.consultation = QtWidgets.QPushButton(self.centralwidget)
        self.consultation.setGeometry(QtCore.QRect(360, 400, 75, 23))
        self.consultation.setObjectName("consultation")
        self.chercher = QtWidgets.QPushButton(self.centralwidget)
        self.chercher.setGeometry(QtCore.QRect(350, 20, 75, 23))
        self.chercher.setObjectName("chercher")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.rdv.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nom Patient"))
        item = self.rdv.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "L\'heur"))
        item = self.rdv.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Telephone"))
        self.label.setText(_translate("MainWindow", "Date"))
        self.supprimer.setText(_translate("MainWindow", "Supprimer"))
        self.ajouter.setText(_translate("MainWindow", "Ajouter"))
        self.consultation.setText(_translate("MainWindow", "Consultation"))
        self.chercher.setText(_translate("MainWindow", "chercher"))
